[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pydsa"
dynamic = ["version"]
description = "Pure Python Data Structures & Algorithms — built from scratch"
requires-python = ">=3.12"
authors = [
    {name = "Sherzod Juraev", email = "juraevsherzod9943@gmail.com"}
]
readme = "README.md"
license = {text = "MIT"}
keywords = ["data-structures", "algorithms", "education", "python", "dsa"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Education",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Education",
    "Topic :: Software Development :: Libraries",
]

[project.optional-dependencies]
dev = [
    "pytest>=9.0",
    "pytest-sugar>=1.0",
    "ruff>=0.6.0",
    "mypy>=1.11",
    "interrogate>=1.7.0",
]
docs = [
    "sphinx>=7.0.0",
    "pydata-sphinx-theme>=0.15.0",
    "sphinx-design>=0.5.0",
    "sphinx-lint>=1.0.0",
    "sphinx-copybutton>=0.5.0",
    "sphinx-notfound-page>=1.1.0",
    "rstcheck>=6.0.0",
    "doc8>=1.0.0",
]
live = [
    "pydsa[docs]",
    "sphinx-autobuild>=2025.8.25",
]
all = [
    "pydsa[dev]",
    "pydsa[live]",
]

[project.urls]
Homepage = "https://github.com/sherzod-juraev/pydsa"

[tool.setuptools.dynamic]
version = {attr = "pydsa.__version__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["pydsa", "pydsa.*"]
exclude = ["tests", "tests.*", "docs", "docs.*"]

[tool.setuptools.package-data]
pydsa = ["**/*.pyi"]

[tool.pytest.ini_options]
minversion = "9.0"
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short --strict-markers --strict-config -p no:warnings"
filterwarnings = [
    "ignore::UserWarning",
]

[tool.ruff]
line-length = 100
target-version = "py312"
include = ["pydsa/**/*.py"]
exclude = [
    "pydsa/__pycache__",
    "pydsa/**/__pycache__",
]

[tool.ruff.lint]
select = [
    "E",
    "D",
    "W",
    "F",
    "I",
    "N",
    "UP",
    "B",
    "SIM",
    "C4",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
python_version = "3.12"
strict = true

[tool.interrogate]
fail-under = 100
verbose = 1
quiet = false
whitelist-regex = []
color = true
exclude = ["docs", "tests"]
ignore-init-method = false
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = false
ignore-nested-functions = false
ignore-nested-classes = false

[tool.rstcheck]
ignore_directives = [
    "button-link",
    "button-ref",
    "card",
    "toctree",
    "automodule",
    "autoclass",
    "autofunction",
    "tab-item",
    "tab-set",
    "grid",
    "grid-item-card",
]
ignore_roles = ["meth", "func", "class", "doc", "ref",]
report_level = "warning"
ignore_paths = [
    "docs/build/*",
]

[tool.doc8]
max-line-length = 100
ignore-path = [
    "docs/build",
    "docs/source/_static",
]

[tool.sphinx-lint]
max-line-length = 100
exclude = [
    "docs/build/*",
]
